### PR TITLE
deps: Update to handlebars 1.0.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
The failed build seems to be due to `handlebars` 1.0 not supporting Rust 1.23 ... I suspect this should be improved upstream as it doesn't seem like a necessary breakage.

**Comment by bheisler** [comment]
Hey, thanks for the pull request!

Could you explain the reasoning behind this change? Technically, bumping the minimum required Rust version is allowed under the compatibility policy, but I don't want to inconvenience existing users without a good reason. Handlebars 0.3 has been working fine as far as I know.

**Comment by waywardmonkeys** [comment]
It was fine ... I just noticed in another project that it built `handlebars` twice because it was using the 1.0 already. But I'm not bothered if we just close this.

**Comment by bheisler** [comment]
In that case, I think I'll just close this for now. Thanks anyway though!

**Pull request closed without merging**
