### PR TITLE
Flyby cleanups

### LINKED ISSUE #203: include LICENSE-* in sub-crates
Unfortunately tarballs on crates.io do not contain it while Apache-2.0 requires that.

Easiest way would be just to create symlinks from appropriate subdirectories.

Thanks for cooperation!

### PR DESCRIPTION
**Pull request by gnzlbg**
* tidy the `ci` scripts a bit
* bump minimum supported rust version to 1.25.0 (probably a breaking change)
* add licenses to the stats and plot libs (closes #203)
* update rustfmt and clippy
* update dependencies
* implement Deref for Sample
* remove some usages of unsafe code (helps with #195)

### CODE REVIEW

**Comment by bheisler** [comment]
Wow, this is great! Thanks a bunch for doing all of this.

Overall, it looks good. I'm concerned about increasing the minimum Rust version, though. Technically, the compatibility policy says we can increase the minimum supported version to 1.26 (though I would prefer to maintain compatibility with 1.23 if it's reasonably practical). You've increased the minimum version to 1.28, though. I'm afraid that won't work. Can you explain why you've increased the minimum version?

The CI failure can be ignored - that test is a bit flaky.

**Comment by gnzlbg** [comment]
> Can you explain why you've increased the minimum version?

So I bumped it to 1.25 first, but once I start removing unsafe code I discovered that `Sample` was invoking undefined behavior because it is not `repr(transparent). Rust 1.28 is the minimum Rust version that supports `repr(transparent)` on stable.

It might be possible to avoid undefined behavior in `Sample` by re-designing the api, e.g., if we change it to `Sample<'a, T>(&'a [T])` instead of the current `&Sample<T>([T])`, but that's going to be a greater breaking change.

**Comment by bheisler** [comment]
Yeah, I'm right there with you. I don't really understand why Sample was designed as it was either - it was like that when I took over maintenance. I suppose I should have refactored a bunch of that stuff.

Regardless, we can't use the `repr(transparent)` tag for a while yet without breaking compatibility. I understand that it's UB, but it's UB that happens to work for now and will probably continue to do so for the near future. I'd prefer to go ahead and convert Sample into a genuinely safe API - `criterion-stats` isn't public API so I don't care about breakage there - but perhaps that should be a separate pull request. For the time being, I'd say just leave it as-is and maybe add a comment to the unsafe spots.

**Comment by gnzlbg** [comment]
Sounds good, I'll ping you when its done. FWIW I think that if one is going to refactor this, the best way would be to just drop criterion stats completely and use one of Rust statistics libraries. They might need some work to support some criterion stats use cases, but that's probably time well spent since other people will take on the maintenance of those parts for you.

**Comment by bheisler** [comment]
> FWIW I think that if one is going to refactor this, the best way would be to just drop criterion stats completely and use one of Rust statistics libraries.

Yeah, that would be nice. I haven't looked into other statistics libraries yet. `criterion-plot` should probably be spun out into its own library as well, if I could find someone who wanted to maintain it.

**Comment by bheisler** [comment]
Thanks for the help!

Rather than make you fix all of the merge conflicts, I've cherry-picked some of your changes onto master.

I decided not to bump the minimum version, since I'm planning to do a breaking-change release soon and I figure I might as well get all of the breakage done at once.

**Pull request closed without merging**
